
name: CraftBeerPi
version: 4.0.8

index_url: /cbpi_ui/static/index.html

port: 8000

mqtt: false
mqtt_host: localhost
mqtt_port: 1883
mqtt_username: ""
mqtt_password: ""

username: cbpi
password: 123

plugins:
- cbpi4ui

